ZIMLET_NAME=com_zimbra_erp_mail_connector
TOPDIR=../..
JSP_BUILD_JARS=\
    ../lib-vnc-openerp/zcs-lib-vnc-openerp.jar	\
    $(ZIMBRA_BUILD_ROOT)/lib/jars/zimbracommon.jar	\
    $(ZIMBRA_BUILD_ROOT)/lib/jars/zimbrastore.jar

include $(TOPDIR)/zcs-zimlet.mk
